// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45e_o5z--54ZRu9-RGZ31cwZkchuUx-4',
    appId: '1:641279537613:web:3a23375dad372e3d405484',
    messagingSenderId: '641279537613',
    projectId: 'chat-ai-app-9ff48',
    authDomain: 'chat-ai-app-9ff48.firebaseapp.com',
    storageBucket: 'chat-ai-app-9ff48.firebasestorage.app',
    measurementId: 'G-918SHPTPJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebmCj-rkQ58Wse2WHux5No1YdMuy94UA',
    appId: '1:641279537613:android:bcd7f2a2efd737b5405484',
    messagingSenderId: '641279537613',
    projectId: 'chat-ai-app-9ff48',
    storageBucket: 'chat-ai-app-9ff48.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB45e_o5z--54ZRu9-RGZ31cwZkchuUx-4',
    appId: '1:641279537613:web:65dd8d4ca323a06d405484',
    messagingSenderId: '641279537613',
    projectId: 'chat-ai-app-9ff48',
    authDomain: 'chat-ai-app-9ff48.firebaseapp.com',
    storageBucket: 'chat-ai-app-9ff48.firebasestorage.app',
    measurementId: 'G-YRSPVZ4F9E',
  );
}
